import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { QuickInsightCard } from "./QuickInsightCard";
import { useState } from "react";

const meta: Meta<typeof QuickInsightCard> = {
  title: "Molecules/QuickInsightCard",
  component: QuickInsightCard,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component: `
QuickInsightCard displays AI-generated contextual insights about headache patterns and user progress.

## Features
- Calming teal/blue gradient background
- Lightbulb icon for visual recognition
- Optional tap-to-refresh functionality
- Responsive, full-width on mobile
- Accessible with keyboard navigation
- Dark mode support

## Use Cases
- Display streak achievements
- Show trend-based insights
- Provide encouraging messages
- Guide users with actionable tips

## Data Source
Insights are generated by the \`dashboardStore.generateInsight()\` method based on:
- Current streak
- This week's headache count
- This week's check-in count
- Trend (improving, stable, declining)
        `,
      },
    },
    a11y: {
      config: {
        rules: [
          {
            id: "color-contrast",
            enabled: true,
          },
        ],
      },
    },
  },
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <div className="w-full max-w-md">
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof QuickInsightCard>;

/**
 * Default state with a welcome message for new users.
 */
export const Default: Story = {
  args: {
    insight: "Welcome! Start tracking to see your progress.",
  },
  parameters: {
    docs: {
      description: {
        story:
          "Default state shown to new users who haven't logged any data yet.",
      },
    },
  },
};

/**
 * Streak achievement insight celebrating user consistency.
 */
export const StreakAchievement: Story = {
  args: {
    insight:
      "Great job! You've logged consistently for 7 days - building great awareness!",
  },
  parameters: {
    docs: {
      description: {
        story:
          "Insight celebrating a 7-day streak, encouraging continued consistency.",
      },
    },
  },
};

/**
 * Milestone achievement for 30+ day streak.
 */
export const LongStreak: Story = {
  args: {
    insight:
      "Amazing! You've maintained a 30-day streak. You're building incredible awareness!",
  },
  parameters: {
    docs: {
      description: {
        story: "Special celebration message for 30+ day streak milestone.",
      },
    },
  },
};

/**
 * Improving trend insight.
 */
export const ImprovingTrend: Story = {
  args: {
    insight: "Great job! Your headache frequency is down this week.",
  },
  parameters: {
    docs: {
      description: {
        story:
          "Positive insight when headache frequency decreased compared to last week.",
      },
    },
  },
};

/**
 * Declining trend insight with supportive message.
 */
export const DecliningTrend: Story = {
  args: {
    insight:
      "Your headache frequency increased this week. Let's identify patterns together.",
  },
  parameters: {
    docs: {
      description: {
        story:
          "Supportive insight when headache frequency increased, guiding user to pattern identification.",
      },
    },
  },
};

/**
 * Check-in encouragement insight.
 */
export const CheckInEncouragement: Story = {
  args: {
    insight:
      "Morning check-ins help identify patterns early. Great proactive tracking!",
  },
  parameters: {
    docs: {
      description: {
        story:
          "Encouraging message for users who regularly complete morning check-ins.",
      },
    },
  },
};

/**
 * No headaches this week - positive reinforcement.
 */
export const NoHeadaches: Story = {
  args: {
    insight: "No headaches logged this week - that's wonderful!",
  },
  parameters: {
    docs: {
      description: {
        story: "Celebratory message when user has no headaches logged.",
      },
    },
  },
};

/**
 * With refresh functionality (interactive).
 */
export const WithRefresh: Story = {
  render: () => {
    const insights = [
      "Welcome! Start tracking to see your progress.",
      "Great job! Your headache frequency is down this week.",
      "You're on a 3-day streak! Consistency is key to understanding your patterns.",
      "Morning check-ins help identify patterns early. Great proactive tracking!",
    ];

    const [index, setIndex] = useState(0);

    const handleRefresh = () => {
      setIndex((prev) => (prev + 1) % insights.length);
    };

    return (
      <QuickInsightCard insight={insights[index]} onRefresh={handleRefresh} />
    );
  },
  parameters: {
    docs: {
      description: {
        story: `
Interactive example with tap-to-refresh functionality.

**Try:**
1. Click the card to cycle through different insights
2. Use keyboard (Tab to focus, Enter/Space to activate)
3. Observe the pulse animation on refresh
        `,
      },
    },
  },
};

/**
 * Long insight text to test text wrapping.
 */
export const LongText: Story = {
  args: {
    insight:
      "You've completed 5 check-ins this week and logged 3 headaches. Consistent tracking reveals helpful patterns - keep it up! The more data you log, the better we can identify your unique triggers and warning signs.",
  },
  parameters: {
    docs: {
      description: {
        story: "Example with longer insight text to demonstrate text wrapping.",
      },
    },
  },
};

/**
 * Dark mode variant.
 */
export const DarkMode: Story = {
  args: {
    insight:
      "Great job! You've logged consistently for 7 days - building great awareness!",
  },
  decorators: [
    (Story) => (
      <div className="bg-gray-900 p-8 rounded-lg">
        <Story />
      </div>
    ),
  ],
  parameters: {
    backgrounds: {
      default: "dark",
    },
    docs: {
      description: {
        story: "Component adapts to dark mode with adjusted gradient colors.",
      },
    },
  },
};

/**
 * Interactive playground.
 */
export const Playground: Story = {
  render: () => {
    const [index, setIndex] = useState(0);
    const insights = [
      "Welcome! Start tracking to see your progress.",
      "Great job! Your headache frequency is down this week.",
      "Amazing! You've maintained a 30-day streak. You're building incredible awareness!",
      "Your headache frequency increased this week. Let's identify patterns together.",
      "Morning check-ins help identify patterns early. Great proactive tracking!",
      "No headaches logged this week - that's wonderful!",
    ];

    return (
      <QuickInsightCard
        insight={insights[index]}
        onRefresh={() => setIndex((prev) => (prev + 1) % insights.length)}
      />
    );
  },
  parameters: {
    docs: {
      description: {
        story: `
Interactive playground to test the component with various insights.

**Try:**
1. Clicking to cycle through different insight types
2. Testing keyboard navigation
3. Observing animations and transitions
        `,
      },
    },
  },
};
